# Generated by Django 4.2.7 on 2025-12-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender_name',
            field=models.CharField(default='Funder Bank', max_length=100),
        ),
    ]
